### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by henriquebjr**

### CODE REVIEW

**Comment by TarabullNinja** [comment]
Hello Henrique. Do I have your full name correct? Henrique Bonajr? I am trying to find your resume connection to this exam so we can begin reviewing.

**Comment by henriquebjr** [comment]
Hi,

My full name is Henrique Luiz Bona Junior.

Best regards.

Em seg., 14 de nov. de 2022 às 13:09, TarabullNinja <
***@***.***> escreveu:

**Comment by TarabullNinja** [comment]
For some reason, I do not see you within our job applications, how did you receive this screening exam?

**Comment by TarabullNinja** [comment]
@henriquebjr We had a delay in your resume being uploaded but we officially have your resume and your screening exam. Thank you, please give the team some time to review.

**Pull request closed without merging**
